env: "local" #development production

server:
  grpc_port: 50050
  host: "localhost"


redis:
  port: 6379
  host: "localhost"
  password: 12345


services:
  users:
    host: "localhost"
    grpc_port: 50051