env: "local" #development production

server:
  grpc_port: 50052
  host: "localhost"

database:
  username: "postgres"
  password: "1234"
  host: "localhost"
  port: 5432
  db_name: "TaskManager"

services:
  auth:
    host: "localhost"
    grpc_port: 50050